def projectName = 'dfoodh-dev'
def version = "0.0.${currentBuild.number}"
def dockerImageTag = "${projectName}:${version}"

def appName = "${params.PROJECT_NAME}"
def imageBuildConfig = appName
def deploymentConfig = appName

pipeline {
  agent {
    label 'maven'
  }
  stages {
    stage('Run unit tests') {
      steps {
        echo "Run unit tests"
        sh 'mvn test'
      }
      post {
        always {
          junit 'target/surefire-reports/*.xml'
        }
      }
    }

    
    stage('Build Image') {
      steps {
        dir("springboot-backend"){
           sh "docker build -t ${dockerImageTag} ."
        }

      }
    }

    stage('Deploy Container To Openshift') {
      steps {
        sh "oc login https://localhost:8443 --username admin --password admin --insecure-skip-tls-verify=true"
        sh "oc project ${projectName} || oc new-project ${projectName}"
        sh "oc delete all --selector app=${projectName} || echo 'Unable to delete all previous openshift resources'"
        sh "oc new-app ${dockerImageTag} -l version=${version}"
        sh "oc expose svc ${projectName}"
      }
    }

    

 
  }
}
