node {
  stage('Preparation') {

    

    // Get the Maven tool.
    // ** NOTE: This 'M3' Maven tool must be configured
    // **       in the global configuration.
    mvnHome = tool 'Maven353'
 }

stage('Build & Test in Jenkins') {
    // Run the maven build
    sh "'${mvnHome}/bin/mvn' test || exit 0"
 }
 
 stage('Build Image') {
      steps {
           sh "docker build -t salmanGurdy ."
      }
    }



   
}
