node {
  stage('Preparation') {

    // Get some code from a GitHub repository
    git "https://github.com/Salman-Mesam/437-FP"

    // Get the Maven tool.
    // ** NOTE: This 'M3' Maven tool must be configured
    // **       in the global configuration.
    mvnHome = tool 'Maven353'
 }

 stage('Build Image') {
      steps {
        dir("springboot-backend"){
           sh "docker build -t ${dockerImageTag} ."
        }

      }
    }

 stage('Build & Test in Jenkins') {
    // Run the maven build
    sh "'${mvnHome}/bin/mvn' test || exit 0"
 }

stage('Run unit tests') {
      steps {
        echo "Run unit tests"
        sh 'mvn test'
      }
      post {
        always {
          junit 'target/surefire-reports/*.xml'
        }
      }
    }

   stage('Generating Report') {
    junit '**/target/surefire-reports/TEST-*.xml'
   }
   

}